version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: mtg_stack_db
    environment:
      POSTGRES_DB: mtgstack
      POSTGRES_USER: kalamalahala
      POSTGRES_PASSWORD: local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: mtgstack_adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: